sudo: required

services:
  - docker

script:
  - sh build.sh

deploy:
  provider: s3
  access_key_id:
    secure: Vibf7S/SYavLur0GYdl9Wna6C7s0jeW1P3R+oknz1MpZAXWrF5esm0+EDEdrt04XOn6RYrrKFgQ4n7THzw6n484xv037mMP/XxjF8sQwkQwF3s2e3PdybT5zJthGHYeQb7vdxB/eJlFhloOvya4H6wApH1X7uLBoUWycz9DJeruNjBPX+TXLVBIcGELXoxf4ArT7Of8llzHq1RWU37JxthQzuHALbIJWNgaAmFdSxuJIMu30J8jg5jhAeQaib+F5F6B+69N/4CnsyC8pELEafpUDBYQopNTtTKofVaImogTk8Je8+y/O8wbrVpAiza53tpKSD2aiY/mytg6f1ye4M+AtQoMNgWmTDaDBBlVpop0dQlRLCtssEr24XRUxvKDhQSYZEnUCeh9z1CEvbZWLgetscAS62z3XMBRclxh2riLjrpNzylJN20HilMSG+D+YKqGywJEHkkhLklCMhclVzxAonA3kE+YorJQRcwa65V3olRYlvDBv/K1tret5ZsxxxzDXrMy2Soz2fejnwOoZEsQ4P3KQTc827TeVK354ZatLsVaYKmHSmLbd4OBTcLqkVUtVMHXrdpCjwM0WzvwkJDwVV95o+RQpl9rgwQUhFR9hCUXPTmBPfzgQybKG4ztFWhrUQM/X0Q2x/yJYTqNAQDGp5PoKnPpSVVbuU2PY6yg=
  secret_access_key:
    secure: InY/vB3ozi2zN73+8sh8gPCRnmxaQBuwyRYxL2JmCKIwEyCe7b38AJvXxJaKSELU7FtdILmIcLgj724UgGmdpCBCCmGiqEWfKxA1vcNQHwhY6v3Ho9+OtmA20A+gm8ruEKXYHHzmR/91ZhTBEsKkWGC7tjjqyL4zBnD/NyUFoMo4BLlp9E38UkUqMXTGc+HVTqFKxmABhQOmxPETSrLCws/c0914CwVuNwdtbWR41iO93YluQ41KThIhJHr4cTqSEiFVYe6opxuCmDtFuD4jrUOZSeMqe5ztlPuxUyJscFlecRfDPr1p4SwXMoKp/G0fPktYpiCmfVbzNAYAPKX2sVMt9wHd9QknER8aQoJ6Kl0Z3cM1dkw+ArKstOvpLqaxE/GGVmCm2gh3IdHWhU44FVCwebQphlL08JuDsHW2pPI7ihtrjg8POH2fE1YhrCNKm9AopglgzdkEcD8iuRz8KUqLfeOL96rrIhzTket+1996rx0udEDHZ7kyhrB1XqdwF9Y4fLFrVohEolBakFGQ4TiVd7GyuXB1+kBW4PZ/fBDXw6Cb837F7xQJEksuPPUhHcHBPukY+QM9YqWtPn3Mk657MysiEdI7R5RUUWB2tsbJZpsKTKY1dq4cCiot4OmQPg6DnLO2Bhg77lYEgeE5gf/rFNVFEEx9Y92PMc/kngk=
  bucket:
    secure: nNLAem/B6YfK3NuDCHH1iESV4p6555yOzQmXh4EcshX8CYjyiWFu7HWJ6rfgA17hgZ4slEQT9JXjkjme+ZXh+uUViBOgyZadZ00NlgGU54m0k8OzXycSRxF6tmQhZwptd5AFpIndeE4zvuOq57qtM4y3BQvVh6uowlmJMOzfL9UZyEl5rkwuxAbhYzUvWtKghyn3QP0jr443YYgaW22KjHkUR0xCND9KJ2uoc6HyjxXkL0RqheV2inkFCISjDgIqjTzNJVKRYox0/FrOeAsCjmkyMnRLRYm5D2o7yPiOh5pNm+A9uu0Frcu+Xc9jzJkpFLERVpsBePLExv/Dq1ticivmdlal7Vsu31U2FFAWvdfMD8GgxexiZ6PWqXbreCJwiH2Ivt4NjGbwe1gM4J3QSZu79mOcocTfnN6XT9e5TLuV5eo9AC924g3CynABSxfok/eVLPmVF7GRud0OdyLTqVaGSsRx75BzWED8d4jRwzqOoIX3frR3se0xVDBafx8pDzih5qE1DnoMQFynyE6aAZGqCNajRxZ4Y65Hxdxa5Z3xQKNWF6vj9DCAgtybLNN4XJKBU2Jm/+R1U72TvN+cj+DLmSI44bsXvH8SC8t54tZnKNkCi04rB2ThuPELadWBGS/54oLeSPc4GEL0VjbSsydSGdyFDvruQdfjRWMKqcw=
  region: eu-west-1
  local-dir: target/site
  upload-dir: poacc/billing/3.0
  acl: public_read
  skip_cleanup: true
  on:
    repo: OpenPEPPOL/peppol-bis-invoice-3
    branch: master
